language: r
sudo: required
warnings_are_errors: true
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libsndfile1-dev
- sudo apt-get install -y fftw3-dev
- sudo apt-get install -y swi-prolog
